source "https://rubygems.org"

gem "i18n"
gem "github-pages"
gem "jekyll"
gem "jekyll-seo-tag"
gem "jekyll-compose"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "bootstrap-sass", "~> 3.3.6"
gem "jekyll-bootstrap-sass"
