---

name: 'dojo do círculo'
title: 'Arthur Alvim'
description: 'Site do dojodocirculo!'
domain: 'dojodocirculo.com.br'
copyright_year: '2017'
email: 'contato@dojodocirculo.com.br'
ga_id: "UA-XXXXX-X"
location: {latitude: -8.050485, longitude: -34.908340}
